hoe-required: false

wheat:
  enabled: true
  wheat-drop-amount: 1
  seed-drops: true
  min-seed-drops: 0
  max-seed-drops: 3

carrot:
  enabled: true
  min-drops: 1
  max-drops: 3

potato:
  enabled: true
  min-drops: 1
  max-drops: 3
  poisonous-potato:
    enabled: true
    drop-percentage: 4
    min-drops: 0
    max-drops: 1

beetroot:
  enabled: true
  beetroot-drop-amount: 1
  seed-drops: true
  min-seed-drops: 0
  max-seed-drops: 3

netherwart:
  enabled: true
  min-drops: 1
  max-drops: 3

sugarcane:
  enabled: true
  multiplier: 1

bamboo:
  enabled: true
  multiplier: 1

melon:
  enabled: true
  min-drops: 3
  max-drops: 7

pumpkin:
  enabled: true
  pumpkin-drop-amount: 1